gText_HowMayIServeYou::
	.string "Welcome!\p"
	.string "How may I serve you?$"

gText_PleaseComeAgain::
	.string "Please come again!$"

gText_KodoughAtCounter::
	.string "(A Kodough is at the counter.\n"
	.string "It seems to run this shop.)$"

gText_KodoughGoodbye::
	.string "(Kodough bows its noggin\n"
	.string "to you as you leave.)$"

gText_WhatDoYouWant::
	.string "Hey.\p"
	.string "What do you want…?$"

gText_SafeTravels::
	.string "Safe travels…$"

gText_PlayerWhatCanIDoForYou::
	.string "{PLAYER}{STRING 5}, welcome!\p"
	.string "What can I do for you?$"
