RustGymDarkLockers_MapScripts::
	.byte 0

RustGymDarkLockers_EventScript_RoxanneRespect::
	msgbox RustGymDarkLockers_Text_RoxanneRespect, MSGBOX_NPC
    end

RustGymDarkLockers_EventScript_WhoIsLivra::
	msgbox RustGymDarkLockers_Text_WhoIsLivra, MSGBOX_NPC
    end

RustGymDarkLockers_EventScript_ImGonnaMakeItOut::
	msgbox RustGymDarkLockers_Text_ImGonnaMakeItOut, MSGBOX_NPC
    end

RustGymDarkLockers_EventScript_IVPottedPlant::
	msgbox RustGymDarkLockers_Text_IVPottedPlant, MSGBOX_NPC
    end

RustGymDarkLockers_EventScript_IThinkImContentHere::
	msgbox RustGymDarkLockers_Text_IThinkImContentHere, MSGBOX_NPC
    end

RustGymDarkLockers_EventScript_MyTextbookHasDoodles::
	msgbox RustGymDarkLockers_Text_MyTextbookHasDoodles, MSGBOX_NPC
    end

RustGymDarkLockers_EventScript_Dakimakura::
	lock
	msgbox RustGymDarkLockers_Text_Dakimakura, MSGBOX_AUTOCLOSE
	release
    end

RustGymDarkLockers_Text_RoxanneRespect:
	.string "Big Sis Roxanne is my ride or die.\n"
	.string "If she says jump, I say, how high?\p"
	.string "Didn't mean to make a dumb poem\n"
	.string "like that. Point is, she is\l"
	.string "one tough cookie. I respect\l"
	.string "her like no one else.$"

RustGymDarkLockers_Text_WhoIsLivra:
	.string "Who the heck is this Livra person?\n"
	.string "Been seein' graffiti sayin' that\l"
	.string "on a bunch of lockers.\p"
	.string "Maybe its code for something.\n"
	.string "Or an alias!$"

RustGymDarkLockers_Text_ImGonnaMakeItOut:
	.string "I am determined to claw my way\n"
	.string "outta this dump. The remedial\l"
	.string "test is gonna get smashed to bits!\p"
	.string "I ain't about this gang nonsense\n"
	.string "like some of the weirdos\l"
	.string "around here. Been avertin' my eyes\l"
	.string "and keepin' em on the prize.$"

RustGymDarkLockers_Text_IVPottedPlant:
	.string "They really gave me crap for\n"
	.string "knocking over a potted plant\l"
	.string "when I was kickboxing.\p"
	.string "That dang plant starts BLEEDING\n"
	.string "after it falls. Turns out?\l"
	.string "It was the school nurse's IV bag??\l"
	.string "WHY was the IV bag disguised as\l"
	.string "a potted plant???$"

RustGymDarkLockers_Text_IThinkImContentHere:
	.string "Y'know... I think I might just\n"
	.string "be content to stay in this wing\l"
	.string "for the forseeable future.\p"
	.string "There's this one girl I talk to.\n"
	.string "She likes to punch me in\l"
	.string "the shoulder. I like that...$"

RustGymDarkLockers_Text_MyTextbookHasDoodles:
	.string "Every public textbook I find\n"
	.string "has doodles in it. Doodles!!\l"
	.string "They're so obscene too.\l"
	.string "How mature!$"

RustGymDarkLockers_Text_Dakimakura:
	.string "(This person is organizing\n"
	.string "her locker.)\p"
	.string "(You catch a glimpse of many\n"
	.string "body-height pillows with pictures\l"
	.string "of anime boys and girls on them.)\p"
	.string "(Gross. End of interaction.)$"
