Route102_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route103_EventScript_ItemGuardSpec::
	finditem ITEM_GUARD_SPEC
	end

Route103_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route104_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route104_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

Route104_EventScript_ItemXAccuracy::
	finditem ITEM_X_ACCURACY
	end

Route104_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route105_EventScript_ItemIron::
	finditem ITEM_IRON
	end

Route106_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route108_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

Route109_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route109_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route110_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route110_EventScript_ItemDireHit::
	finditem ITEM_DIRE_HIT
	end

Route110_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route111_EventScript_ItemTMSandstorm::
	finditem ITEM_TM_SKY_DROP
	end

Route111_EventScript_ItemStardust::
	finditem ITEM_STARDUST
	end

Route111_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

Route111_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route112_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route113_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

Route113_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route113_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route114_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route114_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route114_EventScript_ItemEnergyPowder::
	finditem ITEM_ENERGY_POWDER
	end

Route115_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

Route115_EventScript_ItemTMFocusPunch::
	finditem ITEM_TM_REST
	end

Route115_EventScript_ItemIron::
	finditem ITEM_IRON
	end

Route115_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

Route115_EventScript_ItemHealPowder::
	finditem ITEM_HEAL_POWDER
	end

Route115_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route116_EventScript_ItemXSpecial::
	finditem ITEM_X_SP_ATK
	end

Route116_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

Route116_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

Route116_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

Route116_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route117_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

Route117_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route118_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route119_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route119_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route119_EventScript_ItemLeafStone::
	finditem ITEM_LEAF_STONE
	end

Route119_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route119_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemHyperPotion2::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemElixir2::
	finditem ITEM_ELIXIR
	end

Route120_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route120_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

Route120_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route120_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

Route120_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route121_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route121_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route121_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route123_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

Route123_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

Route123_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route123_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route123_EventScript_ItemRevivalHerb::
	finditem ITEM_REVIVAL_HERB
	end

Route124_EventScript_ItemRedShard::
	finditem ITEM_RED_SHARD
	end

Route124_EventScript_ItemBlueShard::
	finditem ITEM_BLUE_SHARD
	end

Route124_EventScript_ItemYellowShard::
	finditem ITEM_YELLOW_SHARD
	end

Route125_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route126_EventScript_ItemGreenShard::
	finditem ITEM_GREEN_SHARD
	end

Route127_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route127_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route127_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route132_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route132_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route133_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route133_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

Route133_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

Route134_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route134_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

PetalburgCity_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

PetalburgCity_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

MauvilleCity_EventScript_ItemXSpeed::
	finditem ITEM_X_SPEED
	end

RustboroCity_EventScript_ItemXDefend::
	finditem ITEM_X_DEFENSE
	end

LilycoveCity_EventScript_ItemMaxRepel::
	finditem ITEM_MAX_REPEL
	end

MossdeepCity_EventScript_ItemNetBall::
	finditem ITEM_NET_BALL
	end

PetalburgWoods_EventScript_ItemXAttack::
	finditem ITEM_X_ATTACK
	end

PetalburgWoods_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

PetalburgWoods_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

PetalburgWoods_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

RusturfTunnel_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

RusturfTunnel_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

GraniteCave_1F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

GraniteCave_B1F_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

GraniteCave_B2F_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

GraniteCave_B2F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

JaggedPass_EventScript_ItemBurnHeal::
	finditem ITEM_BURN_HEAL
	end

FieryPath_EventScript_ItemFireStone::
	finditem ITEM_FIRE_STONE
	end

FieryPath_EventScript_ItemTMToxic::
	finditem ITEM_TM_TOXIC
	end

MeteorFalls_1F_1R_EventScript_ItemTMIronTail::
	finditem ITEM_TM_IRON_TAIL
	end

MeteorFalls_1F_1R_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

MeteorFalls_1F_1R_EventScript_ItemMoonStone::
	finditem ITEM_MOON_STONE
	end

MeteorFalls_1F_1R_EventScript_ItemPPUP::
	finditem ITEM_PP_UP
	end

MeteorFalls_B1F_2R_EventScript_ItemTMDragonClaw::
	finditem ITEM_TM_DRAGON_CLAW
	end

NewMauville_Inside_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

NewMauville_Inside_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

NewMauville_Inside_EventScript_ItemThunderStone::
	finditem ITEM_THUNDER_STONE
	end

NewMauville_Inside_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

NewMauville_Inside_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

AbandonedShip_Rooms_1F_EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

AbandonedShip_Rooms2_B1F_EventScript_ItemCoolBall::
	finditem ITEM_COOL_BALL
	end

AbandonedShip_Room_B1F_EventScript_ItemTMIceBeam::
	finditem ITEM_TM_ICE_BEAM
	end

AbandonedShip_Rooms2_1F_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey::
	finditem ITEM_STORAGE_KEY
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall::
	finditem ITEM_LUXURY_BALL
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner::
	finditem ITEM_SCANNER
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone::
	finditem ITEM_WATER_STONE
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemTMRainDance::
	finditem ITEM_TM_FEAR_FACTOR
	end

ScorchedSlab_EventScript_ItemTMSunnyDay::
	finditem ITEM_TM_PARTING_SHOT
	end

SafariZone_Northwest_EventScript_ItemTMSolarBeam::
	finditem ITEM_TM_VACUUM_WAVE
	end

SafariZone_North_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

SafariZone_Southwest_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

SafariZone_Northeast_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

SafariZone_Southeast_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

MtPyre_2F_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

MtPyre_3F_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

MtPyre_4F_EventScript_ItemSeaIncense::
	finditem ITEM_SEA_INCENSE
	end

MtPyre_5F_EventScript_ItemLaxIncense::
	finditem ITEM_LAX_INCENSE
	end

MtPyre_6F_EventScript_ItemTMShadowBall::
	finditem ITEM_TM_SHADOW_BALL
	end

MtPyre_Exterior_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

MtPyre_Exterior_EventScript_ItemTMSkillSwap::
	finditem ITEM_TM_BRICK_BREAK
	end

AquaHideout_B1F_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL
	end

AquaHideout_B1F_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

AquaHideout_B1F_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

AquaHideout_B2F_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

AquaHideout_B2F_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL      // Unused
	end

Route119_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route119_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

Route119_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal::
	finditem ITEM_ICE_HEAL
	end

ShoalCave_LowTideIceRoom_EventScript_ItemTMHail::
	finditem ITEM_TM_TRICK_ROOM
	end

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce::
	finditem ITEM_NEVER_MELT_ICE
	end

SeafloorCavern_Room9_EventScript_ItemTMEarthquake::
	finditem ITEM_TM_EARTHQUAKE
	end

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail::
	finditem ITEM_ORANGE_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail::
	finditem ITEM_WAVE_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail::
	finditem ITEM_SHADOW_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail::
	finditem ITEM_WOOD_MAIL
	end

Route110_TrickHousePuzzle4_EventScript_ItemMechMail::
	finditem ITEM_MECH_MAIL
	end

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail::
	finditem ITEM_GLITTER_MAIL
	end

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail::
	finditem ITEM_TROPIC_MAIL
	end

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail::
	finditem ITEM_BEAD_MAIL
	end

VictoryRoad_1F_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

VictoryRoad_1F_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

VictoryRoad_B1F_EventScript_ItemTMPsychic::
	finditem ITEM_TM_PSYCHIC
	end

VictoryRoad_B1F_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

VictoryRoad_B2F_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

ArtisanCave_B1F_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

ArtisanCave_1F_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

MagmaHideout_1F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

MagmaHideout_2F_2R_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

MagmaHideout_2F_2R_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

MagmaHideout_3F_1R_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

MagmaHideout_3F_2R_EventScript_ItemPPMax::
	finditem ITEM_PP_MAX
	end

MagmaHideout_4F_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

MagmaHideout_3F_3R_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

Route121_EventScript_ItemTMDragonTail::
	finditem ITEM_TM_DRAGON_TAIL
	end

Route123_EventScript_ItemTMSkyDrop::
	finditem ITEM_TM_SKY_DROP
	end

Route123_EventScript_ItemTMAuroraBeam::
	finditem ITEM_TM_AURORA_BEAM
	end

SkyPillarNew_EventScript_ItemSodaPop::
	finditem ITEM_SODA_POP
	end

SkyPillarNew_EventScript_ItemTinyMushroom::
	finditem ITEM_TINY_MUSHROOM
	end

SkyPillarInteriors_EventScript_ItemSodaPop::
	finditem ITEM_SODA_POP
	end

SkyPillarInteriors_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

SkyPillarInteriors_EventScript_ItemAntidote::
	finditem ITEM_ANTIDOTE
	end

SkyPillarInteriors_EventScript_ItemSodaPop2::
	finditem ITEM_SODA_POP
	end

SkyPillarInteriors_EventScript_ItemRepel2::
	finditem ITEM_REPEL
	end

Flotshore_EventScript_ItemAntidote::
	finditem ITEM_ANTIDOTE
	end

Flotshore_EventScript_ItemSodaPop::
	finditem ITEM_SODA_POP
	end

Flotshore_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

Flotshore_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

Flotshore_EventScript_ItemOranBerry::
	finditem ITEM_ORAN_BERRY
	end

PiratesGrotto_EventScript_ItemCursedAmulet::
	finditem ITEM_CURSED_AMULET
	end

PiratesGrotto_EventScript_ItemBigNugget1::
	finditem ITEM_BIG_NUGGET
	end

PiratesGrotto_EventScript_ItemBigNugget2::
	finditem ITEM_BIG_NUGGET
	end

BasalinCoast_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

BasalinCoast_EventScript_ItemSodaPop::
	finditem ITEM_SODA_POP
	end

BasalinCoast_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

BasalinCoast_EventScript_ItemAntidote::
	finditem ITEM_ANTIDOTE
	end

BasalinCoast_EventScript_ItemIceHeal::
	finditem ITEM_ICE_HEAL
	end

BasalinCoast_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

NewSooto_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

NewSooto_EventScript_ItemIceHeal::
	finditem ITEM_ICE_HEAL
	end

NewSooto_EventScript_ItemSodaPop::
	finditem ITEM_SODA_POP
	end

NewSooto_EventScript_ItemTinyMushroom::
	finditem ITEM_TINY_MUSHROOM
	end

MangrottoTunnel_EventScript_ItemPokeball::
	finditem ITEM_POKE_BALL
	end

MangrottoTunnel_EventScript_ItemAwakening::
	finditem ITEM_AWAKENING
	end

MangrottoTunnel_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

MangrottoTunnel_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

MangrottoTunnel_EventScript_ItemRepeatball::
	finditem ITEM_REPEAT_BALL
	end

MangrottoTunnel_EventScript_ItemSilverPowder::
	finditem ITEM_SILVER_POWDER
	end

Route126_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route126_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

Route126_EventScript_ItemStardust::
	finditem ITEM_STARDUST
	end

Route126_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route126_EventScript_ItemLureBall::
	finditem ITEM_LURE_BALL
	end

CosmossSpaceCenter_EventScript_ItemStardust::
	finditem ITEM_STARDUST
	end

MossdeepCity_EventScript_ItemPPersimBerry::
	finditem ITEM_PERSIM_BERRY
	end

MossdeepCity_EventScript_ItemPRevive::
	finditem ITEM_REVIVE
	end

MossdeepCity_EventScript_ItemPEther::
	finditem ITEM_ETHER
	end

MossdeepCity_EventScript_ItemPPotion::
	finditem ITEM_POTION
	end

MossdeepCity_EventScript_ItemPFullHeal::
	finditem ITEM_FULL_HEAL
	end

MossdeepCity_EventScript_ItemPRevive2::
	finditem ITEM_REVIVE
	end

MossdeepCity_EventScript_ItemPStardust::
	finditem ITEM_STARDUST
	end

Route125_EventScript_ItemPSharpBeak::
	finditem ITEM_SHARP_BEAK
	end

NewSunbeach_EventScript_ItemPBlackGlasses::
	finditem ITEM_BLACK_GLASSES
	end

OzoneLilycoveHQ_EventScript_ItemPCellBattery::
	finditem ITEM_CELL_BATTERY
	end

TheColdMines_EventScript_ItemPHardStone::
	finditem ITEM_HARD_STONE
	end

Route121_EventScript_ItemPNeverMeltIce::
	finditem ITEM_NEVER_MELT_ICE
	end

MtPyre_1F_EventScript_ItemPSpellTag::
	finditem ITEM_SPELL_TAG
	end

Route120_EventScript_ItemPProtectPads::
	finditem ITEM_PROTECTIVE_PADS
	end

Route120_EventScript_ItemPCharcoal::
	finditem ITEM_CHARCOAL
	end

ScutillHuts_EventScript_ItemPPeskyPlush::
	finditem ITEM_PESKY_PLUSH
	end

CanopourWilds_EventScript_ItemPQuickClaw::
	finditem ITEM_QUICK_CLAW
	end

CanopourBushes_EventScript_ItemPBigRoot::
	finditem ITEM_BIG_ROOT
	end

Route113_EventScript_ItemPThunderStone::
	finditem ITEM_THUNDER_STONE
	end

MasoriedHike_EventScript_ItemPLightClay::
	finditem ITEM_LIGHT_CLAY
	end

PerplumeMaze_EventScript_ItemPChupacabra::
	finditem ITEM_CHUPACABRA
	end

CrimneyClimb_EventScript_ItemPKingsRock::
	finditem ITEM_KINGS_ROCK
	end

CrimneyClimb_EventScript_ItemPAirBalloon::
	finditem ITEM_AIR_BALLOON
	end

CrimneyClimb_EventScript_ItemPRockyHelmet::
	finditem ITEM_ROCKY_HELMET
	end

JaggroPass_EventScript_ItemPRoomExtender::
	finditem ITEM_ROOM_EXTENDER
	end

MidneorFallsCave_EventScript_ItemPMoonStone::
	finditem ITEM_MOON_STONE
	end

SootopolisCastle_EventScript_ItemPDragonFang::
	finditem ITEM_DRAGON_FANG
	end

FieryPath_EventScript_ItemPAssaultVest::
	finditem ITEM_ASSAULT_VEST
	end

LavaridgeInt_EventScript_ItemPPoisonBarb::
	finditem ITEM_POISON_BARB
	end

CrimneyCaldera_EventScript_ItemPHeatRock::
	finditem ITEM_HEAT_ROCK
	end

SweltornTransitionCave_EventScript_ItemPSoftSand::
	finditem ITEM_SOFT_SAND
	end

SweltornDesert_EventScript_ItemPDustGoggles::
	finditem ITEM_SAFETY_GOGGLES
	end

MauvilleNew_EventScript_ItemPTwistedSpoon::
	finditem ITEM_TWISTED_SPOON
	end

MauvilleNew_EventScript_ItemPZoomLens::
	finditem ITEM_ZOOM_LENS
	end

MauvilleNew_EventScript_ItemPWideLens::
	finditem ITEM_WIDE_LENS
	end

HatchloamField_EventScript_ItemPMiracleSeed::
	finditem ITEM_MIRACLE_SEED
	end

CyclingRoad_EventScript_ItemPScopeLens::
	finditem ITEM_SCOPE_LENS
	end

CyclingRoad_EventScript_ItemPTerrainCoat::
	finditem ITEM_TERRAIN_EXTENDER
	end

Maintenance_EventScript_ItemPBlackSludge::
	finditem ITEM_BLACK_SLUDGE
	end

Maintenance_EventScript_ItemPMetalCoat::
	finditem ITEM_METAL_COAT
	end

Route126_EventScript_ItemPMagnet::
	finditem ITEM_MAGNET
	end

SouthMossdeep_EventScript_ItemPFairyFeather::
	finditem ITEM_FAIRY_FEATHER
	end

NavigulfWaves_EventScript_ItemPBrightPowder::
	finditem ITEM_BRIGHT_POWDER
	end

ShoalCaveNewFloor2_EventScript_ItemPDawnStone::
	finditem ITEM_DAWN_STONE
	end

StraeSeapath_EventScript_ItemPSmoothRock::
	finditem ITEM_SMOOTH_ROCK
	end

MidneorFalls_EventScript_ItemPDuskStone::
	finditem ITEM_DUSK_STONE
	end

DewfordNew_EventScript_ItemPBoxingGlove::
	finditem ITEM_PUNCHING_GLOVE
	end

SailorsPauseShips_EventScript_ItemPRedCard::
	finditem ITEM_RED_CARD
	end

SailorsPauseShips_EventScript_ItemPThroatSpray::
	finditem ITEM_THROAT_SPRAY
	end

StraeSeapathUnderwater_EventScript_ItemPCorrodeMod::
	finditem ITEM_CORRODE_MOD
	end

ShoalCaveNewFloor2_EventScript_ItemPIcyRock::
	finditem ITEM_ICY_ROCK
	end

StraeSeapath_EventScript_ItemPShinyStone::
	finditem ITEM_SHINY_STONE
	end

DetermaniteBeach_EventScript_ItemPMetronome::
	finditem ITEM_METRONOME
	end

DetermaniteBeach_EventScript_ItemPBlackBelt::
	finditem ITEM_BLACK_BELT
	end

WishwellOcean_EventScript_ItemPLeftovers::
	finditem ITEM_LEFTOVERS
	end

WishwellOcean_EventScript_ItemPMysticWater::
	finditem ITEM_MYSTIC_WATER
	end

RustburgWharf_EventScript_ItemPSilkScarf::
	finditem ITEM_SILK_SCARF
	end

MidneorNadir_EventScript_ItemPDampRock::
	finditem ITEM_DAMP_ROCK
	end

UnduraTunnels_EventScript_ItemPMuscleBand::
	finditem ITEM_MUSCLE_BAND
	end

UnduraTunnels_EventScript_ItemPWiseGlasses::
	finditem ITEM_WISE_GLASSES
	end

PetalburgNew_EventScript_ItemPClearAmulet::
	finditem ITEM_CLEAR_AMULET
	end

PetalburgWoodsNew_EventScript_ItemPCovertCLoak::
	finditem ITEM_COVERT_CLOAK
	end

NovicesWalk_EventScript_ItemPAThing::
	finditem ITEM_A_THING
	end

PendingDev_EventScript_ItemPAbilityGuard::
	finditem ITEM_ABILITY_SHIELD
	end

TechnicalMachines_EventScript_ItemPTMThunderWave::
	finditem ITEM_TM_THUNDER_WAVE
	end

TechnicalMachines_EventScript_ItemPTMStickyWeb::
	finditem ITEM_TM_STICKY_WEB
	end

TechnicalMachines_EventScript_ItemPTMRetaliate::
	finditem ITEM_TM_RETALIATE
	end

TechnicalMachines_EventScript_ItemPTMRockSlide::
	finditem ITEM_TM_ROCK_SLIDE
	end

TechnicalMachines_EventScript_ItemPTMHyperVoice::
	finditem ITEM_TM_HYPER_VOICE
	end

TechnicalMachines_EventScript_ItemPTMGlaciate::
	finditem ITEM_TM_GLACIATE
	end

TechnicalMachines_EventScript_ItemPTMFlorescence::
	finditem ITEM_TM_JUNGLE_HEALING
	end

TechnicalMachines_EventScript_ItemPTMGyroBall::
	finditem ITEM_TM_GYRO_BALL
	end

TechnicalMachines_EventScript_ItemPTMKnockOff::
	finditem ITEM_TM_KNOCK_OFF
	end

TechnicalMachines_EventScript_ItemPTMBrickBreak::
	finditem ITEM_TM_BRICK_BREAK
	end

TechnicalMachines_EventScript_ItemPTMDazzleGleam::
	finditem ITEM_TM_DAZZLING_GLEAM
	end

TechnicalMachines_EventScript_ItemPTMAuraSphere::
	finditem ITEM_TM_AURA_SPHERE
	end

TechnicalMachines_EventScript_ItemPTMDarkPulse::
	finditem ITEM_TM_DARK_PULSE
	end

TechnicalMachines_EventScript_ItemPTMBodySlam::
	finditem ITEM_TM_BODY_SLAM
	end

TechnicalMachines_EventScript_ItemPTMVenoshock::
	finditem ITEM_TM_VENOSHOCK
	end

TechnicalMachines_EventScript_ItemPTMPsyshock::
	finditem ITEM_TM_PSYSHOCK
	end

TechnicalMachines_EventScript_ItemPTMWillpower::
	finditem ITEM_TM_WILLPOWER
	end

TechnicalMachines_EventScript_ItemPTMIronHead::
	finditem ITEM_TM_IRON_HEAD
	end

TechnicalMachines_EventScript_ItemPTMShadowClaw::
	finditem ITEM_TM_SHADOW_CLAW
	end

TechnicalMachines_EventScript_ItemPTMZenHeadbutt::
	finditem ITEM_TM_ZEN_HEADBUTT
	end

TechnicalMachines_EventScript_ItemPTMLunge::
	finditem ITEM_TM_LUNGE
	end

TechnicalMachines_EventScript_ItemPTMFlameLash::
	finditem ITEM_TM_FIRE_LASH
	end

TechnicalMachines_EventScript_ItemPTMSeedBomb::
	finditem ITEM_TM_SEED_BOMB
	end

TechnicalMachines_EventScript_ItemPTMDragonPulse::
	finditem ITEM_TM_DRAGON_PULSE
	end

TechnicalMachines_EventScript_ItemPTMFoulPlay::
	finditem ITEM_TM_FOUL_PLAY
	end

TechnicalMachines_EventScript_ItemPTMRazorWind::
	finditem ITEM_TM_RAZOR_WIND
	end

TechnicalMachines_EventScript_ItemPTMThroatChop::
	finditem ITEM_TM_THROAT_CHOP
	end

TechnicalMachines_EventScript_ItemPTMIcicleCrash::
	finditem ITEM_TM_ICICLE_CRASH
	end

TechnicalMachines_EventScript_ItemPTMPhaseForce::
	finditem ITEM_TM_PHANTOM_FORCE
	end

TechnicalMachines_EventScript_ItemPTMAquaTail::
	finditem ITEM_TM_AQUA_TAIL
	end

TechnicalMachines_EventScript_ItemPTMDireClaw::
	finditem ITEM_TM_DIRE_CLAW
	end

TechnicalMachines_EventScript_ItemPTMThunderbolt::
	finditem ITEM_TM_THUNDERBOLT
	end

TechnicalMachines_EventScript_ItemPTMPlayRough::
	finditem ITEM_TM_PLAY_ROUGH
	end

TechnicalMachines_EventScript_ItemPTMFlamethrower::
	finditem ITEM_TM_FLAMETHROWER
	end

TechnicalMachines_EventScript_ItemPTMIceBeam::
	finditem ITEM_TM_ICE_BEAM
	end

TechnicalMachines_EventScript_ItemPTMPsychic::
	finditem ITEM_TM_PSYCHIC
	end

TechnicalMachines_EventScript_ItemPTMMoonblast::
	finditem ITEM_TM_MOONBLAST
	end

TechnicalMachines_EventScript_ItemPTMEarthquake::
	finditem ITEM_TM_EARTHQUAKE
	end

TechnicalMachines_EventScript_ItemPTMZapCannon::
	finditem ITEM_TM_ZAP_CANNON
	end

TechnicalMachines_EventScript_ItemPTMRagingFury::
	finditem ITEM_TM_RAGING_FURY
	end

Route125_EventScript_ItemPPPUp::
	finditem ITEM_PP_UP
	end

Route125_EventScript_ItemPSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route125_EventScript_ItemPRevive::
	finditem ITEM_REVIVE
	end

NewSunbeach_EventScript_ItemPPokeDoll::
	finditem ITEM_POKE_DOLL
	end

NewSunbeach_EventScript_ItemPSuperPotion::
	finditem ITEM_SUPER_POTION
	end

NewSunbeach_EventScript_ItemPCoralCrown::
	finditem ITEM_CORAL_CROWN
	end

NewSunbeach_EventScript_ItemPPPUp::
	finditem ITEM_PP_UP
	end

NewSunbeach_EventScript_ItemPBigMushroom::
	finditem ITEM_BIG_MUSHROOM
	end

LilycoveCity_EventScript_ItemPFullHeal::
	finditem ITEM_FULL_HEAL
	end

LilycoveCity_EventScript_ItemPRevive::
	finditem ITEM_REVIVE
	end

LilycoveCity_EventScript_ItemPPPUp::
	finditem ITEM_PP_UP
	end

LilycoveCity_EventScript_ItemPAbilityCookie::
	finditem ITEM_ABILITY_CAPSULE
	end

TheColdMines_EventScript_ItemPNugget::
	finditem ITEM_NUGGET
	end

TheColdMines_EventScript_ItemPCoralCrown::
	finditem ITEM_CORAL_CROWN
	end

TheColdMines_EventScript_ItemPPokedoll::
	finditem ITEM_POKE_DOLL
	end

TheColdMines_EventScript_ItemPIceHeal::
	finditem ITEM_ICE_HEAL
	end

TheColdMines_EventScript_ItemPSuperPotion::
	finditem ITEM_SUPER_POTION
	end

Route121_EventScript_ItemPCoralCrown::
	finditem ITEM_CORAL_CROWN
	end

Route121_EventScript_ItemPPPUp::
	finditem ITEM_PP_UP
	end

Route121_EventScript_ItemPRelaxant::
	finditem ITEM_RELAXANT
	end

Route121_EventScript_ItemPXSpeed::
	finditem ITEM_X_SPEED
	end

Route123_EventScript_ItemPRelaxant::
	finditem ITEM_RELAXANT
	end

Route123_EventScript_ItemPRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route123_EventScript_ItemPPPUp::
	finditem ITEM_PP_UP
	end

Route123_EventScript_ItemPXSpAtk::
	finditem ITEM_X_SP_ATK
	end

Route123_EventScript_ItemPElixir::
	finditem ITEM_ELIXIR
	end

MtPyre_1F_EventScript_ItemPPokedoll::
	finditem ITEM_POKE_DOLL
	end

MtPyre_1F_EventScript_ItemPMaxEther::
	finditem ITEM_MAX_ETHER
	end

MtPyre_1F_EventScript_ItemPSuperPotion::
	finditem ITEM_SUPER_POTION
	end

MtPyre_2F_EventScript_ItemPCoralCrown::
	finditem ITEM_CORAL_CROWN
	end

MtPyre_2F_EventScript_ItemPGuardSpec::
	finditem ITEM_GUARD_SPEC
	end

MtPyre_2F_EventScript_ItemPSpDef::
	finditem ITEM_X_SP_DEF
	end

MtPyre_2F_EventScript_ItemPPPUp::
	finditem ITEM_PP_UP
	end

Route122_EventScript_ItemPRevive::
	finditem ITEM_REVIVE
	end

Route120_EventScript_ItemPEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

Route120_EventScript_ItemPCarrotHorn::
	finditem ITEM_CARROT_HORN
	end

Route120_EventScript_ItemPSeriousMint::
	finditem ITEM_SERIOUS_MINT
	end

Route120_EventScript_ItemPPPUp::
	finditem ITEM_PP_UP
	end

Route120_EventScript_ItemPXDefense::
	finditem ITEM_X_DEFENSE
	end

ScutillHuts_EventScript_ItemPAbilityCookie::
	finditem ITEM_ABILITY_CAPSULE
	end

ScutillHuts_EventScript_ItemPPPUp::
	finditem ITEM_PP_UP
	end

ScutillHuts_EventScript_ItemPSuperPotion::
	finditem ITEM_SUPER_POTION
	end

ScutillHuts_EventScript_ItemPMaxRepel::
	finditem ITEM_MAX_REPEL
	end

ScutillHuts_EventScript_ItemPMaxEther::
	finditem ITEM_MAX_ETHER
	end

ScutillHuts_EventScript_ItemPRevive::
	finditem ITEM_REVIVE
	end

ScutillHuts_EventScript_ItemPBigMushroom::
	finditem ITEM_BIG_MUSHROOM
	end

ScutillHuts_EventScript_ItemPEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

CanopourWilds_EventScript_ItemPCoralCrown::
	finditem ITEM_CORAL_CROWN
	end

CanopourWilds_EventScript_ItemPFullHeal::
	finditem ITEM_FULL_HEAL
	end

PerplumeMaze_EventScript_ItemPXAttack::
	finditem ITEM_X_ATTACK
	end

PerplumeMaze_EventScript_ItemPDireHit::
	finditem ITEM_DIRE_HIT
	end

PerplumeMaze_EventScript_ItemPMaxRepel::
	finditem ITEM_MAX_REPEL
	end

PerplumeMaze_EventScript_ItemPCarrotHorn::
	finditem ITEM_CARROT_HORN
	end

PerplumeMaze_EventScript_ItemPAdamantMint::
	finditem ITEM_ADAMANT_MINT
	end

ScuttillSecretTreeHouse_EventScript_ItemPNestBall::
	finditem ITEM_NEST_BALL
	end

OzoneInstitute_EventScript_ItemPGoldTooth::
	finditem ITEM_GOLD_TOOTH
	end

OzoneInstitute_EventScript_ItemPBigMushroom::
	finditem ITEM_BIG_MUSHROOM
	end

OzoneInstitute_EventScript_ItemPHyperPotion::
	finditem ITEM_HYPER_POTION
	end

MasoriedHike_EventScript_ItemPXSpAtk::
	finditem ITEM_X_SP_ATK
	end

MasoriedHike_EventScript_ItemPModestMint::
	finditem ITEM_MODEST_MINT
	end

Route113_EventScript_ItemPGoldTooth::
	finditem ITEM_GOLD_TOOTH
	end

Route113_EventScript_ItemPNugget::
	finditem ITEM_NUGGET
	end

Route113_EventScript_ItemPPPUp::
	finditem ITEM_PP_UP
	end

Route113_EventScript_ItemPAbilityCookie::
	finditem ITEM_ABILITY_CAPSULE
	end

Route113_EventScript_ItemPMaxRepel::
	finditem ITEM_MAX_REPEL
	end

Route113_EventScript_ItemPCarrotHorn::
	finditem ITEM_CARROT_HORN
	end

CrimneyClimb_EventScript_ItemPCoralCrown::
	finditem ITEM_CORAL_CROWN
	end

CrimneyClimb_EventScript_ItemPGoldTooth::
	finditem ITEM_GOLD_TOOTH
	end

CrimneyClimb_EventScript_ItemPXSpeed::
	finditem ITEM_X_SPEED
	end

CrimneyClimb_EventScript_ItemPNugget::
	finditem ITEM_NUGGET
	end

CrimneyClimb_EventScript_ItemPRareCandy::
	finditem ITEM_RARE_CANDY
	end

CrimneyClimb_EventScript_ItemPAbilityCookie::
	finditem ITEM_ABILITY_CAPSULE
	end

JaggroPass_EventScript_ItemPGoldTooth::
	finditem ITEM_GOLD_TOOTH
	end

JaggroPass_EventScript_ItemPJollyMint::
	finditem ITEM_JOLLY_MINT
	end

JaggroPass_EventScript_ItemPPPUp::
	finditem ITEM_PP_UP
	end

JaggroPass_EventScript_ItemPFullHeal::
	finditem ITEM_FULL_HEAL
	end

JaggroPass_EventScript_ItemPHyperPotion::
	finditem ITEM_HYPER_POTION
	end

JaggroPass_EventScript_ItemPXDefense::
	finditem ITEM_X_DEFENSE
	end

FallarborNew_EventScript_ItemPSeriousMint::
	finditem ITEM_SERIOUS_MINT
	end

FallarborNew_EventScript_ItemPCarrotHorn::
	finditem ITEM_CARROT_HORN
	end

FallarborNew_EventScript_ItemPMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

MidneorFallsCave_EventScript_ItemPOrbitBall::
	finditem ITEM_MOON_BALL
	end

MidneorFallsCave_EventScript_ItemPStarPiece::
	finditem ITEM_STAR_PIECE
	end

MidneorFallsCave_EventScript_ItemPDuskBall::
	finditem ITEM_DUSK_BALL
	end

FieryPath_EventScript_ItemPCoralCrown1::
	finditem ITEM_CORAL_CROWN
	end

FieryPath_EventScript_ItemPCoralCrown2::
	finditem ITEM_CORAL_CROWN
	end

FieryPath_EventScript_ItemPCoralCrown3::
	finditem ITEM_CORAL_CROWN
	end

FieryPath_EventScript_ItemPPPUp::
	finditem ITEM_PP_UP
	end

FieryPath_EventScript_ItemPRareBone::
	finditem ITEM_RARE_BONE
	end

FieryPath_EventScript_ItemPEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

FieryPath_EventScript_ItemPDireHit::
	finditem ITEM_DIRE_HIT
	end

LavaridgeInt_EventScript_ItemPMaxEther::
	finditem ITEM_MAX_ETHER
	end

LavaridgeInt_EventScript_ItemPCarefulMint::
	finditem ITEM_CAREFUL_MINT
	end

LavaridgeInt_EventScript_ItemPAbilityCookie::
	finditem ITEM_ABILITY_CAPSULE
	end

LavaridgeInt_EventScript_ItemPXSpDef::
	finditem ITEM_X_SP_DEF
	end

SootopolisCastle_EventScript_ItemPRareBone::
	finditem ITEM_RARE_BONE
	end

SootopolisCastle_EventScript_ItemPRareCandy::
	finditem ITEM_RARE_CANDY
	end

SootopolisCastle_EventScript_ItemPCoralCrown::
	finditem ITEM_CORAL_CROWN
	end

PiratesGrotto_EventScript_ItemPBigNugget::
	finditem ITEM_BIG_NUGGET
	end

PiratesGrotto_EventScript_ItemPGoldTooth::
	finditem ITEM_GOLD_TOOTH
	end

SweltornDesert_EventScript_ItemPGoldTooth::
	finditem ITEM_GOLD_TOOTH
	end

SweltornDesert_EventScript_ItemPPPMax::
	finditem ITEM_PP_MAX
	end

SweltornDesert_EventScript_ItemPCoralCrown::
	finditem ITEM_CORAL_CROWN
	end

SweltornDesert_EventScript_ItemPStardust::
	finditem ITEM_STARDUST
	end

SweltornDesert_EventScript_ItemPFullHeal::
	finditem ITEM_FULL_HEAL
	end

SweltornDesert_EventScript_ItemPHyperPotion::
	finditem ITEM_HYPER_POTION
	end

SweltornDesert_EventScript_ItemPMaxEther::
	finditem ITEM_MAX_ETHER
	end

SweltornDesert_EventScript_ItemPMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

SweltornPalace_EventScript_ItemPRareBone::
	finditem ITEM_RARE_BONE
	end

SweltornPalace_EventScript_ItemPBitterRoot::
	finditem ITEM_ENERGY_ROOT
	end

SweltornPalace_EventScript_ItemPNugget::
	finditem ITEM_NUGGET
	end

SweltornPalaceOutside_EventScript_ItemPEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

SweltornPalaceOutside_EventScript_ItemPRareCandy::
	finditem ITEM_RARE_CANDY
	end

SweltornPalaceOutside_EventScript_ItemPLuxuryBall::
	finditem ITEM_LUXURY_BALL
	end

SweltornTransitionCave_EventScript_ItemPXAccuracy::
	finditem ITEM_X_ACCURACY
	end

SweltornTransitionCave_EventScript_ItemPLaxMint::
	finditem ITEM_LAX_MINT
	end

SweltornTransitionCave_EventScript_ItemPAbilityCookie::
	finditem ITEM_ABILITY_CAPSULE
	end

SweltornTransitionHallway_EventScript_ItemPTimerBall::
	finditem ITEM_TIMER_BALL
	end

SweltornTransitionHallway_EventScript_ItemPQuickBall::
	finditem ITEM_QUICK_BALL
	end

MauvilleNew_EventScript_ItemPAbilityCookie::
	finditem ITEM_ABILITY_CAPSULE
	end

MauvilleNew_EventScript_ItemPGoldTooth::
	finditem ITEM_GOLD_TOOTH
	end

MauvilleNew_EventScript_ItemPGuardSpec::
	finditem ITEM_GUARD_SPEC
	end

HatchloamField_EventScript_ItemPCarrotHorn1::
	finditem ITEM_CARROT_HORN
	end

HatchloamField_EventScript_ItemPCarrotHorn2::
	finditem ITEM_CARROT_HORN
	end

HatchloamField_EventScript_ItemPPPUp::
	finditem ITEM_PP_UP
	end

HatchloamField_EventScript_ItemPTimidMint::
	finditem ITEM_TIMID_MINT
	end

HatchloamField_EventScript_ItemPRevive::
	finditem ITEM_REVIVE
	end

TrickHouseMainPortion_EventScript_ItemPFullHeal::
	finditem ITEM_FULL_HEAL
	end

TrickHouseLeverRooms_EventScript_ItemPPPMax::
	finditem ITEM_PP_MAX
	end

TrickHouseLeverRooms_EventScript_ItemPXAttack::
	finditem ITEM_X_ATTACK
	end

TrickHouseLeverRooms_EventScript_ItemPGoldTooth::
	finditem ITEM_GOLD_TOOTH
	end

SouthernIsland_EventScript_ItemPMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

CyclingRoad_EventScript_ItemPXSpeed::
	finditem ITEM_X_SPEED
	end

CyclingRoad_EventScript_ItemPCarrotHorn::
	finditem ITEM_CARROT_HORN
	end

CyclingRoad_EventScript_ItemPHyperPotion::
	finditem ITEM_HYPER_POTION
	end

CyclingRoad_EventScript_ItemPMaxEther::
	finditem ITEM_MAX_ETHER
	end

SeaMauville_EventScript_ItemPElixir::
	finditem ITEM_ELIXIR
	end

SeaMauville_EventScript_ItemPMaxRepel::
	finditem ITEM_MAX_REPEL
	end

Maintenance_EventScript_ItemPUltraBall::
	finditem ITEM_ULTRA_BALL
	end

Maintenance_EventScript_ItemPFastBall::
	finditem ITEM_FAST_BALL
	end

Maintenance_EventScript_ItemPDireHit::
	finditem ITEM_DIRE_HIT
	end

NewMauville_Inside_EventScript_ItemPMaxRepel::
	finditem ITEM_MAX_REPEL
	end

NewMauville_Inside_EventScript_ItemPXDefense::
	finditem ITEM_X_DEFENSE
	end

VerdanturfNew_EventScript_ItemPRareCandy::
	finditem ITEM_RARE_CANDY
	end

VerdanturfNew_EventScript_ItemPCarrotHorn::
	finditem ITEM_CARROT_HORN
	end

VerdanturfNew_EventScript_ItemPLonelyMint::
	finditem ITEM_LONELY_MINT
	end

SlateportShore_EventScript_ItemPMaxPotion::
	finditem ITEM_MAX_POTION
	end

SlateportShore_EventScript_ItemPMaxEther::
	finditem ITEM_MAX_ETHER
	end

DewfordNew_EventScript_ItemPCarrotHorn::
	finditem ITEM_CARROT_HORN
	end

StraeSeapath_EventScript_ItemPXSpAtk::
	finditem ITEM_X_SP_ATK
	end

StraeSeapath_EventScript_ItemPGoldTooth::
	finditem ITEM_GOLD_TOOTH
	end

StraeSeapath_EventScript_ItemPNugget::
	finditem ITEM_NUGGET
	end

Flotshore_EventScript_ItemPPPMax::
	finditem ITEM_PP_MAX
	end

SailorsPauseShips_EventScript_ItemPAbilityCookie::
	finditem ITEM_ABILITY_CAPSULE
	end

SailorsPauseShips_EventScript_ItemPMaxPotion::
	finditem ITEM_MAX_POTION
	end

NewSunbeach_EventScript_ItemPCoralCrownPostSurf::
	finditem ITEM_CORAL_CROWN
	end

NewSunbeach_EventScript_ItemPStarPiece::
	finditem ITEM_STAR_PIECE
	end

ShoalCaveNewFloor1_EventScript_ItemPRareCandy::
	finditem ITEM_RARE_CANDY
	end

ShoalCaveNewFloor2_EventScript_ItemPHeavyBall::
	finditem ITEM_HEAVY_BALL
	end

NavigulfUnderwater_EventScript_ItemPCoralCrown::
	finditem ITEM_CORAL_CROWN
	end

NavigulfUnderwater_EventScript_ItemPDuskBall::
	finditem ITEM_DUSK_BALL
	end

StraeSeapathUnderwater_EventScript_ItemPPPMax::
	finditem ITEM_PP_MAX
	end

StraeSeapathUnderwater_EventScript_ItemPMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

StraeSeapathUnderwater_EventScript_ItemPCoralCrown::
	finditem ITEM_CORAL_CROWN
	end

DetermaniteBeach_EventScript_ItemPXSpDef::
	finditem ITEM_X_SP_DEF
	end

DetermaniteBeach_EventScript_ItemPCoolBall::
	finditem ITEM_COOL_BALL
	end

DetermaniteBeach_EventScript_ItemPMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

DetermaniteBeach_EventScript_ItemPCoralCrown::
	finditem ITEM_CORAL_CROWN
	end

DetermaniteQuarry_EventScript_ItemPLoveBall::
	finditem ITEM_LOVE_BALL
	end

DetermaniteQuarB1F_EventScript_ItemPExtrapolator::
	finditem ITEM_EXTRAPOLATOR
	end

DetermaniteQuarB1F_EventScript_ItemPPPMax::
	finditem ITEM_PP_MAX
	end

DetermaniteQuarB1F_EventScript_ItemPRareCandy::
	finditem ITEM_RARE_CANDY
	end

WishwellOcean_EventScript_ItemPCarrotHorn::
	finditem ITEM_CARROT_HORN
	end

WishwellOcean_EventScript_ItemPAbilityCookie::
	finditem ITEM_ABILITY_CAPSULE
	end

WishwellOcean_EventScript_ItemPQuietMint::
	finditem ITEM_QUIET_MINT
	end

RustburgWharf_EventScript_ItemPGoldTooth::
	finditem ITEM_GOLD_TOOTH
	end

RustburgWharf_EventScript_ItemPMaxRepel::
	finditem ITEM_MAX_REPEL
	end

RustburgWharf_EventScript_ItemPMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

RustburgWharf_EventScript_ItemPPPMax::
	finditem ITEM_PP_MAX
	end

RustburgWharf_EventScript_ItemPFullRestore::
	finditem ITEM_FULL_RESTORE
	end

UnduraTunnels_EventScript_ItemPMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

UnduraTunnelsDeep_EventScript_ItemPCoralCrown::
	finditem ITEM_CORAL_CROWN
	end

UnduraTunnelsDeep_EventScript_ItemPStarPiece::
	finditem ITEM_STAR_PIECE
	end

UnduraTunnelsDeep_EventScript_ItemPBeastBall::
	finditem ITEM_BEAST_BALL
	end

MidneorFalls_EventScript_ItemPStarPiece::
	finditem ITEM_STAR_PIECE
	end

MidneorFalls_EventScript_ItemPCometShard::
	finditem ITEM_COMET_SHARD
	end

MidneorFalls_EventScript_ItemPMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

MidneorFalls_EventScript_ItemPMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

MidneorFalls_EventScript_ItemPPPMax::
	finditem ITEM_PP_MAX
	end

MidneorFalls_EventScript_ItemPRareCandy::
	finditem ITEM_RARE_CANDY
	end

MidneorFalls_EventScript_ItemPFullRestore::
	finditem ITEM_FULL_RESTORE
	end

MidneorFalls_EventScript_ItemPDreamBall::
	finditem ITEM_DREAM_BALL
	end

RustboroNew_EventScript_ItemPAbilityCookie::
	finditem ITEM_ABILITY_CAPSULE
	end

RustboroNew_EventScript_ItemPGoldTooth::
	finditem ITEM_GOLD_TOOTH
	end

PetalburgNew_EventScript_ItemPCalmMint::
	finditem ITEM_CALM_MINT
	end

PetalburgWoodsNew_EventScript_ItemPStarPiece::
	finditem ITEM_STAR_PIECE
	end

PetalburgWoodsNew_EventScript_ItemPAbilityCookie::
	finditem ITEM_ABILITY_CAPSULE
	end

PetalburgWoodsNew_EventScript_ItemPPokeDoll::
	finditem ITEM_POKE_DOLL
	end

OldaleNew_EventScript_ItemPCarrotHorn::
	finditem ITEM_CARROT_HORN
	end

NoviceWalk_EventScript_ItemPFullRestore::
	finditem ITEM_FULL_RESTORE
	end

NoviceWalk_EventScript_ItemPMaxEther::
	finditem ITEM_MAX_ETHER
	end

NoviceWalk_EventScript_ItemPRareCandy::
	finditem ITEM_RARE_CANDY
	end

NoviceWalk_EventScript_ItemPLevelBall::
	finditem ITEM_LEVEL_BALL
	end

PendingDev_EventScript_ItemPPPMax::
	finditem ITEM_PP_MAX
	end

EverGrandeTransitionCave_EventScript_ItemPGoldTooth::
	finditem ITEM_GOLD_TOOTH
	end

EverGrandeTransitionCave_EventScript_ItemPFullRestore::
	finditem ITEM_FULL_RESTORE
	end

EverGrandeRoad_EventScript_ItemPCoralCrown::
	finditem ITEM_CORAL_CROWN
	end

EverGrandeRoad_EventScript_ItemPCarrotHorn::
	finditem ITEM_CARROT_HORN
	end

EverGrandeRoad_EventScript_ItemPMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

EverGrandeRoad_EventScript_ItemPGoldBall1::
	finditem ITEM_PARK_BALL
	end

EverGrandeRoad_EventScript_ItemPGoldBall2::
	finditem ITEM_PARK_BALL
	end

EverGrandeRoad_EventScript_ItemPBigNugget::
	finditem ITEM_BIG_NUGGET
	end

EverGrandeRoad_EventScript_ItemPPPMax::
	finditem ITEM_PP_MAX
	end

EverGrandeRoad_EventScript_ItemPMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

EverGrandePeak_EventScript_ItemPMaxRevive::
	finditem ITEM_MAX_REVIVE
	end
