SeasideCasinoVIPLounges_MapScripts::
	.byte 0

SeasideCasinoVIPLounges_EventScript_Akagi::
    trainerbattle_single TRAINER_P_AKAGI, SeasideCasinoVIPLounges_Text_AkagiIntro, SeasideCasinoVIPLounges_Text_AkagiDefeated
    msgbox SeasideCasinoVIPLounges_Text_AkagiPostBattle, MSGBOX_AUTOCLOSE
    end

SeasideCasinoVIPLounges_EventScript_Moneywell::
    trainerbattle_single TRAINER_P_MONEYWELL, SeasideCasinoVIPLounges_Text_MoneywellIntro, SeasideCasinoVIPLounges_Text_MoneywellDefeated
    msgbox SeasideCasinoVIPLounges_Text_MoneywellPostBattle, MSGBOX_AUTOCLOSE
    end

SeasideCasinoVIPLounges_EventScript_Dante::
    trainerbattle_single TRAINER_P_DANTE, SeasideCasinoVIPLounges_Text_DanteIntro, SeasideCasinoVIPLounges_Text_DanteDefeated
    msgbox SeasideCasinoVIPLounges_Text_DantePostBattle, MSGBOX_AUTOCLOSE
    end

SeasideCasinoVIPLounges_EventScript_Shinjiro::
    trainerbattle_single TRAINER_P_SHINJIRO, SeasideCasinoVIPLounges_Text_ShinjiroIntro, SeasideCasinoVIPLounges_Text_ShinjiroDefeated
    msgbox SeasideCasinoVIPLounges_Text_ShinjiroPostBattle, MSGBOX_AUTOCLOSE
    end

SeasideCasinoVIPLounges_EventScript_Skyler::
    trainerbattle_single TRAINER_P_SKYLER, SeasideCasinoVIPLounges_Text_SkylerIntro, SeasideCasinoVIPLounges_Text_SkylerDefeated
    msgbox SeasideCasinoVIPLounges_Text_SkylerPostBattle, MSGBOX_AUTOCLOSE
    end

SeasideCasinoVIPLounges_EventScript_Walter::
    trainerbattle_single TRAINER_P_WALTER, SeasideCasinoVIPLounges_Text_WalterIntro, SeasideCasinoVIPLounges_Text_WalterDefeated
    msgbox SeasideCasinoVIPLounges_Text_WalterPostBattle, MSGBOX_AUTOCLOSE
    end

SeasideCasinoVIPLounges_EventScript_Knuckles::
    trainerbattle_single TRAINER_P_KNUCKLES, SeasideCasinoVIPLounges_Text_KnucklesIntro, SeasideCasinoVIPLounges_Text_KnucklesDefeated
    msgbox SeasideCasinoVIPLounges_Text_KnucklesPostBattle, MSGBOX_AUTOCLOSE
    end

SeasideCasinoVIPLounges_EventScript_Fingers::
    trainerbattle_single TRAINER_P_FINGERS, SeasideCasinoVIPLounges_Text_FingersIntro, SeasideCasinoVIPLounges_Text_FingersDefeated
    msgbox SeasideCasinoVIPLounges_Text_FingersPostBattle, MSGBOX_AUTOCLOSE
    end

SeasideCasinoVIPLounges_Text_AkagiIntro:
	.string "intro$"

SeasideCasinoVIPLounges_Text_AkagiDefeated:
	.string "defeat$"

SeasideCasinoVIPLounges_Text_AkagiPostBattle:
	.string "post$"

SeasideCasinoVIPLounges_Text_MoneywellIntro:
	.string "intro$"

SeasideCasinoVIPLounges_Text_MoneywellDefeated:
	.string "defeat$"

SeasideCasinoVIPLounges_Text_MoneywellPostBattle:
	.string "post$"

SeasideCasinoVIPLounges_Text_DanteIntro:
	.string "intro$"

SeasideCasinoVIPLounges_Text_DanteDefeated:
	.string "defeat$"

SeasideCasinoVIPLounges_Text_DantePostBattle:
	.string "post$"

SeasideCasinoVIPLounges_Text_ShinjiroIntro:
	.string "intro$"

SeasideCasinoVIPLounges_Text_ShinjiroDefeated:
	.string "defeat$"

SeasideCasinoVIPLounges_Text_ShinjiroPostBattle:
	.string "post$"

SeasideCasinoVIPLounges_Text_SkylerIntro:
	.string "intro$"

SeasideCasinoVIPLounges_Text_SkylerDefeated:
	.string "defeat$"

SeasideCasinoVIPLounges_Text_SkylerPostBattle:
	.string "post$"

SeasideCasinoVIPLounges_Text_WalterIntro:
	.string "intro$"

SeasideCasinoVIPLounges_Text_WalterDefeated:
	.string "defeat$"

SeasideCasinoVIPLounges_Text_WalterPostBattle:
	.string "post$"

SeasideCasinoVIPLounges_Text_KnucklesIntro:
	.string "intro$"

SeasideCasinoVIPLounges_Text_KnucklesDefeated:
	.string "defeat$"

SeasideCasinoVIPLounges_Text_KnucklesPostBattle:
	.string "post$"

SeasideCasinoVIPLounges_Text_FingersIntro:
	.string "intro$"

SeasideCasinoVIPLounges_Text_FingersDefeated:
	.string "defeat$"

SeasideCasinoVIPLounges_Text_FingersPostBattle:
	.string "post$"
